version: ~> 1.0

os: linux

dist: xenial

language: python

python:
  - 3.6
  - 3.7
  - 3.8

git:
  depth: false

before_install:

  # install lilypond:
  - lilypond_url=http://lilypond.org/download/binaries/linux-64/
  - lilypond_source=lilypond-2.19.84-1.linux-64.sh
  - wget -q -O /tmp/lilypond $lilypond_url/$lilypond_source
  - sh /tmp/lilypond --batch

  # clone & install abjad:
  - git clone https://github.com/Abjad/abjad.git /tmp/abjad
  - pip install /tmp/abjad
  - export MYPYPATH=$MYPYPATH:/tmp/abjad

  # log environment variables:
  - echo $MYPYPATH
  - echo $PATH
  - echo $PYTHONPATH
  - echo $TRAVIS_BUILD_DIR
  - echo $TRAVIS_PYTHON_VERSION

install:
  - pip install -e .[test]

  # log versions:
  - black --version
  - flake8 --version
  - isort --version
  - mypy --version
  - pip --version
  - pytest --version

script:
  - make black-check
  - make flake8
  - make isort-check
  - make mypy
  - make pytest

after_success:
  - pip install --quiet coveralls
  - coveralls
